import manifest from "@/lib/data/image-manifest.json";

export type ImageSource = { src: string; width: number; height: number };
export type ImageVariant = ImageSource & { srcSet: ImageSource[] };
export type PhotoVariantName = "hero" | "tile";

type ManifestRecord = { alt: string; title: string; hero?: ImageVariant; tile?: ImageVariant };

const PHOTOS = manifest as Record<string, ManifestRecord>;

export type PhotoKey = keyof typeof manifest;

/** A processed photo from lib/data/image-manifest.json (generated by scripts/process-images.mjs). */
export type Photo = ImageVariant & { alt: string; title?: string };

export function getPhoto(key: PhotoKey, variant: PhotoVariantName = "hero"): Photo {
  const record = PHOTOS[key];
  const image = record?.[variant];
  if (!image) throw new Error(`No "${variant}" variant for photo "${key}"`);
  return { ...image, alt: record.alt, title: record.title || undefined };
}

export function toSrcSet(image: Pick<ImageVariant, "srcSet">): string {
  return image.srcSet.map((s) => `${encodeURI(s.src)} ${s.width}w`).join(", ");
}
